"""b1 initial schema

Revision ID: df06ac2c7719
Revises: 
Create Date: 2026-07-20 18:07:36.458075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df06ac2c7719'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_catalog',
    sa.Column('groups', sa.JSON(), nullable=True),
    sa.Column('product_codes', sa.JSON(), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('uploaded_at', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('defect_log',
    sa.Column('defect_id', sa.String(length=64), nullable=False),
    sa.Column('inv_mc', sa.String(length=64), nullable=False),
    sa.Column('serial_no', sa.String(length=120), nullable=True),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('defect_id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_index(op.f('ix_defect_log_inv_mc'), 'defect_log', ['inv_mc'], unique=False)
    op.create_table('delivery_schedule',
    sa.Column('vessel_id', sa.String(length=64), nullable=False),
    sa.Column('mid_cat', sa.String(length=100), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('req_qty', sa.Integer(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    sa.UniqueConstraint('vessel_id', 'mid_cat', name='uq_delivery_vessel_midcat')
    )
    op.create_index(op.f('ix_delivery_schedule_vessel_id'), 'delivery_schedule', ['vessel_id'], unique=False)
    op.create_table('fat_comment',
    sa.Column('fat_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('done_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_index(op.f('ix_fat_comment_fat_id'), 'fat_comment', ['fat_id'], unique=False)
    op.create_table('fat_comment_codes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('fat_history',
    sa.Column('fat_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_index(op.f('ix_fat_history_fat_id'), 'fat_history', ['fat_id'], unique=False)
    op.create_table('fat_master',
    sa.Column('vessel_id', sa.String(length=64), nullable=False),
    sa.Column('class', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scm_ready_from', sa.Date(), nullable=True),
    sa.Column('scm_ready_to', sa.Date(), nullable=True),
    sa.Column('scm_note', sa.Text(), nullable=True),
    sa.Column('fat_date', sa.Date(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('inspector', sa.String(length=100), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('product', sa.String(length=200), nullable=True),
    sa.Column('flag', sa.String(length=100), nullable=True),
    sa.Column('yard', sa.String(length=100), nullable=True),
    sa.Column('sn', sa.String(length=120), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    sa.UniqueConstraint('vessel_id', 'class', name='uq_fat_vessel_class')
    )
    op.create_index(op.f('ix_fat_master_vessel_id'), 'fat_master', ['vessel_id'], unique=False)
    op.create_table('fat_ref_docs',
    sa.Column('class', sa.String(length=20), nullable=False),
    sa.Column('doc_title', sa.String(length=300), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_index(op.f('ix_fat_ref_docs_class'), 'fat_ref_docs', ['class'], unique=False)
    op.create_table('file_object',
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('table_ref', sa.String(length=64), nullable=True),
    sa.Column('record_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_table('incoming_header',
    sa.Column('incoming_id', sa.String(length=64), nullable=False),
    sa.Column('po_id', sa.String(length=30), nullable=True),
    sa.Column('po_ref_no', sa.String(length=30), nullable=True),
    sa.Column('incoming_date', sa.Date(), nullable=True),
    sa.Column('ordered_qty', sa.Integer(), nullable=False),
    sa.Column('total_scanned', sa.Integer(), nullable=False),
    sa.Column('inspector', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vessel', sa.String(length=100), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incoming_id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_index(op.f('ix_incoming_header_po_id'), 'incoming_header', ['po_id'], unique=False)
    op.create_table('incoming_line',
    sa.Column('incoming_id', sa.String(length=64), nullable=False),
    sa.Column('mc_code', sa.String(length=64), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('serial_no', sa.String(length=120), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_index(op.f('ix_incoming_line_incoming_id'), 'incoming_line', ['incoming_id'], unique=False)
    op.create_index(op.f('ix_incoming_line_serial_no'), 'incoming_line', ['serial_no'], unique=False)
    op.create_table('inspection_cert',
    sa.Column('cert_id', sa.String(length=64), nullable=False),
    sa.Column('incoming_id', sa.String(length=64), nullable=False),
    sa.Column('po_id', sa.String(length=30), nullable=True),
    sa.Column('cert_no', sa.String(length=200), nullable=True),
    sa.Column('issued_by', sa.String(length=200), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cert_id'),
    sa.UniqueConstraint('incoming_id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('inventory',
    sa.Column('mc_code', sa.String(length=64), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=300), nullable=True),
    sa.Column('serial_no', sa.String(length=120), nullable=False),
    sa.Column('po_id', sa.String(length=30), nullable=True),
    sa.Column('po_ref_no', sa.String(length=30), nullable=True),
    sa.Column('supplier_code', sa.String(length=50), nullable=True),
    sa.Column('incoming_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rack_location', sa.String(length=100), nullable=True),
    sa.Column('vessel_assigned', sa.String(length=64), nullable=True),
    sa.Column('vessel_code_assigned', sa.String(length=100), nullable=True),
    sa.Column('cert_id', sa.String(length=64), nullable=True),
    sa.Column('manual_entry', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    sa.UniqueConstraint('mc_code'),
    sa.UniqueConstraint('serial_no')
    )
    op.create_index(op.f('ix_inventory_item_code'), 'inventory', ['item_code'], unique=False)
    op.create_index(op.f('ix_inventory_po_id'), 'inventory', ['po_id'], unique=False)
    op.create_index(op.f('ix_inventory_status'), 'inventory', ['status'], unique=False)
    op.create_table('med_cert',
    sa.Column('no', sa.String(length=50), nullable=True),
    sa.Column('order_old', sa.String(length=100), nullable=True),
    sa.Column('cert_no', sa.String(length=100), nullable=True),
    sa.Column('order_new', sa.String(length=100), nullable=True),
    sa.Column('medf_cert_new', sa.String(length=100), nullable=True),
    sa.Column('sn', sa.String(length=120), nullable=True),
    sa.Column('audit', sa.String(length=100), nullable=True),
    sa.Column('obt_fat', sa.String(length=100), nullable=True),
    sa.Column('medf_status', sa.String(length=100), nullable=True),
    sa.Column('hull_no', sa.String(length=100), nullable=True),
    sa.Column('shipyard', sa.String(length=100), nullable=True),
    sa.Column('dl_vessel', sa.String(length=100), nullable=True),
    sa.Column('medb_cert_no', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('outgoing_log',
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('inv_mc', sa.String(length=64), nullable=False),
    sa.Column('inv_sn', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('vessel_id', sa.String(length=64), nullable=True),
    sa.Column('vessel_code', sa.String(length=100), nullable=True),
    sa.Column('mid_cat', sa.String(length=100), nullable=True),
    sa.Column('pic', sa.String(length=100), nullable=True),
    sa.Column('team', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('inspector', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('inspection_memo', sa.Text(), nullable=True),
    sa.Column('cancel_of', sa.String(length=64), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    sa.UniqueConstraint('log_id')
    )
    op.create_index(op.f('ix_outgoing_log_action'), 'outgoing_log', ['action'], unique=False)
    op.create_index(op.f('ix_outgoing_log_inv_mc'), 'outgoing_log', ['inv_mc'], unique=False)
    op.create_table('po_counter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', name='uq_po_counter_year')
    )
    op.create_table('po_header',
    sa.Column('po_ref_no', sa.String(length=30), nullable=False),
    sa.Column('vessel_code', sa.String(length=100), nullable=True),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('supplier_email', sa.String(length=200), nullable=True),
    sa.Column('vessel_code_no', sa.String(length=100), nullable=True),
    sa.Column('vessel_name', sa.String(length=200), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pic', sa.String(length=100), nullable=True),
    sa.Column('terms', sa.JSON(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    sa.UniqueConstraint('po_ref_no')
    )
    op.create_index(op.f('ix_po_header_supplier_code'), 'po_header', ['supplier_code'], unique=False)
    op.create_table('po_line',
    sa.Column('po_id', sa.String(length=30), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordered_qty', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_index(op.f('ix_po_line_item_code'), 'po_line', ['item_code'], unique=False)
    op.create_index(op.f('ix_po_line_po_id'), 'po_line', ['po_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('supplier_email', sa.String(length=200), nullable=True),
    sa.Column('supplier_tel', sa.String(length=50), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id'),
    sa.UniqueConstraint('supplier_code')
    )
    op.create_table('vessel_bom',
    sa.Column('vessel_id', sa.String(length=64), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=300), nullable=True),
    sa.Column('required_qty', sa.Integer(), nullable=False),
    sa.Column('gubun', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('mid_cat', sa.String(length=100), nullable=True),
    sa.Column('registered_date', sa.Date(), nullable=True),
    sa.Column('shortage_ack', sa.Boolean(), nullable=False),
    sa.Column('shortage_ack_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_index(op.f('ix_vessel_bom_item_code'), 'vessel_bom', ['item_code'], unique=False)
    op.create_index(op.f('ix_vessel_bom_vessel_id'), 'vessel_bom', ['vessel_id'], unique=False)
    op.create_table('vessel_docs',
    sa.Column('vessel_id', sa.String(length=64), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('doc_title', sa.String(length=300), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_index(op.f('ix_vessel_docs_vessel_id'), 'vessel_docs', ['vessel_id'], unique=False)
    op.create_table('vessel_master',
    sa.Column('vessel_type', sa.String(length=20), nullable=False),
    sa.Column('shipping_company', sa.String(length=200), nullable=True),
    sa.Column('vessel_name', sa.String(length=200), nullable=False),
    sa.Column('vessel_classes', sa.JSON(), nullable=True),
    sa.Column('ship_type', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('flag', sa.String(length=100), nullable=True),
    sa.Column('yard', sa.String(length=100), nullable=True),
    sa.Column('imo_number', sa.String(length=50), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('registered_at', sa.Date(), nullable=True),
    sa.Column('supply_product', sa.String(length=200), nullable=True),
    sa.Column('construction_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('dl_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('series_no', sa.String(length=50), nullable=True),
    sa.Column('seatrial_start', sa.Date(), nullable=True),
    sa.Column('seatrial_end', sa.Date(), nullable=True),
    sa.Column('commission_start', sa.Date(), nullable=True),
    sa.Column('commission_end', sa.Date(), nullable=True),
    sa.Column('cxop_remark', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_table('vessel_notes',
    sa.Column('vessel_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    op.create_index(op.f('ix_vessel_notes_vessel_id'), 'vessel_notes', ['vessel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vessel_notes_vessel_id'), table_name='vessel_notes')
    op.drop_table('vessel_notes')
    op.drop_table('vessel_master')
    op.drop_index(op.f('ix_vessel_docs_vessel_id'), table_name='vessel_docs')
    op.drop_table('vessel_docs')
    op.drop_index(op.f('ix_vessel_bom_vessel_id'), table_name='vessel_bom')
    op.drop_index(op.f('ix_vessel_bom_item_code'), table_name='vessel_bom')
    op.drop_table('vessel_bom')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_po_line_po_id'), table_name='po_line')
    op.drop_index(op.f('ix_po_line_item_code'), table_name='po_line')
    op.drop_table('po_line')
    op.drop_index(op.f('ix_po_header_supplier_code'), table_name='po_header')
    op.drop_table('po_header')
    op.drop_table('po_counter')
    op.drop_index(op.f('ix_outgoing_log_inv_mc'), table_name='outgoing_log')
    op.drop_index(op.f('ix_outgoing_log_action'), table_name='outgoing_log')
    op.drop_table('outgoing_log')
    op.drop_table('med_cert')
    op.drop_index(op.f('ix_inventory_status'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_po_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_item_code'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_table('inspection_cert')
    op.drop_index(op.f('ix_incoming_line_serial_no'), table_name='incoming_line')
    op.drop_index(op.f('ix_incoming_line_incoming_id'), table_name='incoming_line')
    op.drop_table('incoming_line')
    op.drop_index(op.f('ix_incoming_header_po_id'), table_name='incoming_header')
    op.drop_table('incoming_header')
    op.drop_table('file_object')
    op.drop_index(op.f('ix_fat_ref_docs_class'), table_name='fat_ref_docs')
    op.drop_table('fat_ref_docs')
    op.drop_index(op.f('ix_fat_master_vessel_id'), table_name='fat_master')
    op.drop_table('fat_master')
    op.drop_index(op.f('ix_fat_history_fat_id'), table_name='fat_history')
    op.drop_table('fat_history')
    op.drop_table('fat_comment_codes')
    op.drop_index(op.f('ix_fat_comment_fat_id'), table_name='fat_comment')
    op.drop_table('fat_comment')
    op.drop_index(op.f('ix_delivery_schedule_vessel_id'), table_name='delivery_schedule')
    op.drop_table('delivery_schedule')
    op.drop_index(op.f('ix_defect_log_inv_mc'), table_name='defect_log')
    op.drop_table('defect_log')
    op.drop_table('bom_catalog')
    # ### end Alembic commands ###
